name: Django CI

on:
  push:
    branches: [ master ]
  #schedule:
  #- cron: '5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    #strategy:
      #max-parallel: 4
      #matrix:
        #python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.2'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./crontest/createfile
      run: |
        python createtestfile.py
    
